fix: sp1 key not found for programs other than provers (#712)

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -93,7 +93,7 @@ jobs:
 
             # Extract sp1 value using jq
             SP1_VALUE=$(echo "$PARAMS_OUTPUT" | jq -r '.rollup_vk.sp1')
-            echo "sp1_value=\"$SP1_VALUE\"" >> "$GITHUB_OUTPUT"
+            echo "sp1_value=$SP1_VALUE" >> "$GITHUB_OUTPUT"
             echo "SP1 verification key: $SP1_VALUE"
 
             # Build prover with sp1 features
@@ -110,13 +110,20 @@ jobs:
           docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${SHORT_TAG}"
       - name: Extract SP1 Value
         id: extract-sp1-value
+        env:
+          SP1_VALUE: ${{ steps.build-and-push.outputs.sp1_value }}
         run: |
-          if [ -n "$SP1_VALUE" ]; then
-            echo "sp1_value=$SP1_VALUE" >> "$GITHUB_OUTPUT"
-          else
-            echo "Error: Failed to extract SP1 value from parameters"
-            exit 1
+          # store sp1 value only if the matrix program is prover-client
+          if [ "${{ matrix.program }}" == "prover-client" ]; then
+            if [ -n "$SP1_VALUE" ]; then
+              echo "sp1_value=$SP1_VALUE" >> "$GITHUB_OUTPUT"
+            else
+              # the process must exit if we do not have the verification key when prover is built
+              echo "Error: Failed to extract SP1 value from parameters"
+              exit 1
+            fi
           fi
+
   update-helm-values:
     name: Update Helm Values
     needs: [build-and-push]
