Fix sequencer crash tests (#653)
* feat: sync missing EL blocks from CL blocks on startup
port from #417

* move crash_* tests to own group
add test case for sync_event_new_tip crash
fix for sync_event_new_tip crash testcase:
construct fcm data from chainstate

* fix: process skipped l2 blocks during fcm startup
enable crash_advance_consensus_state test

* add more logs

* fix docker compose build and run

* refactor: move unprocessed block logic to own function

* update logging

* replace bail! with custom error types

* add more logs

* upload logs as build artifact if fntest fails

* reduce timeout

* keep only service.log in fntest artifact

* write logs during second fn test run

* ci: dont save logs for funcTestsRun1 fails only
debug logging is not enabled there
also add functional test logs

* use independent env for problematic fn test

diff --git a/.github/workflows/functional.yml b/.github/workflows/functional.yml
--- a/.github/workflows/functional.yml
+++ b/.github/workflows/functional.yml
@@ -118,20 +118,54 @@ jobs:
       - name: Run functional tests (1)
         id: funcTestsRun1
         continue-on-error: true
+        env:
+          NO_COLOR: "1"
         run: |
           NEWPATH="$(realpath target/debug/)"
           export PATH="${NEWPATH}:${PATH}"
           which strata-client
           cd functional-tests && poetry run python entry.py
 
-      # Run again just to be sure as some tests are flaky
+      # Run again just to be sure as some tests are flaky, with more logging
       - name: Run functional tests (2)
+        id: funcTestsRun2
         if: steps.funcTestsRun1.outcome == 'failure'
+        continue-on-error: true
+        env:
+          RUST_LOG: "trace,hyper=warn,soketto=warn,jsonrpsee-server=warn,mio=warn"
+          NO_COLOR: "1"
+          RUST_BACKTRACE: "1"
+          LOG_LEVEL: "debug"
         run: |
           NEWPATH="$(realpath target/debug/)"
           export PATH="${NEWPATH}:${PATH}"
           which strata-client
           cd functional-tests && poetry run python entry.py
+      - name: Zip log files on failure
+        if: steps.funcTestsRun2.outcome == 'failure'
+        # Create a zip archive (logs.zip) that includes only service.log files,
+        # preserving the folder structure starting from functional-tests/_dd
+        # NOTE: Entire _dd ends up hundreds of MBs, so keep only logs (still huge...).
+        run: |
+          # service logs
+          find functional-tests/_dd -type f -name "service.log" | zip -@ logs.zip
+          # functional test logs
+          zip -r logs.zip functional-tests/_dd -i '*/logs/*.log'
+      - name: Upload logs as build artifact on failure
+        if: steps.funcTestsRun2.outcome == 'failure'
+        uses: actions/upload-artifact@v4
+        with:
+          name: fntest_dd
+          path: logs.zip
+          retention-days: 30
+          if-no-files-found: error
+          compression-level: 0 # already compressed
+      - name: Fail job if functional tests fail
+        if: steps.funcTestsRun2.outcome == 'failure'
+        run: |
+          echo "Functional tests failed"
+          exit 1
+
 
   functional-tests-success:
     name: Check that all checks pass
